### ISSUE TITLE
Downtime because of disk full - reduce nginx log verbosity

### ISSUE THREAD

**Issue by ymartin59** [SynoCommunity/spkrepo#67]
Nginx container stdout contains access log and is aggregate to:
/var/lib/docker/containers/5ed5af0c0c7ea40322d631b8153bfadbeafdd9f261571023a48d0f0a335d49d7/5ed5af0c0c7ea40322d631b8153bfadbeafdd9f261571023a48d0f0a335d49d7-json.log 
up to 21 GiB

A container restart cleans it out but it would be better to amend docker-compose.yml with directives to either log access log to system volume with proper log rotation, or else simply discard access logs (until we do anything useful with them)

**Comment by publicarray** [comment]
I've used the following in almost all of my docker setups to stop the very same issue. Hope that helps

`docker-compose.yml`

```
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
```
